In [1]:
import pandas as pd
columnname=['name']
raw_data=pd.read_excel(r"C:\Users\HP\Downloads\Association Rules\Association Rules\Online retail.xlsx", header=None)
raw_data.head()

                                                   0
0  shrimp,almonds,avocado,vegetables mix,green gr...
1                             burgers,meatballs,eggs
2                                            chutney
3                                     turkey,avocado
4  mineral water,milk,energy bar,whole wheat rice...

In [2]:
raw_data.isnull().sum()

0    0
dtype: int64

In [3]:
raw_data.shape

(7501, 1)

In [4]:
from mlxtend.preprocessing import TransactionEncoder
transactions=[]
for i in range(len(raw_data)):
    # Read the first cell of each row (Index 0)
    row_string = str(raw_data.iloc[i, 0]) 
    # Split by comma and clean up whitespace/empty values
    items = [item.strip() for item in row_string.split(',') if item.strip() and item.strip().lower() != 'nan']
    if items:
        transactions.append(items)
#print(transactions)
te=TransactionEncoder()
te_array=te.fit(transactions).transform(transactions)
processed_data=pd.DataFrame(te_array,columns=te.columns_)
processed_data.head(10)

,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,body spray,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,True,True,False,True,False,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [12]:
from mlxtend.frequent_patterns import apriori, association_rules

freq_itemsets = apriori(processed_data,min_support=0.003,use_colnames=True)
#print(freq_itemsets.head())

rules=association_rules(freq_itemsets,metric="lift",min_threshold=3)
#print(rules.head())


filtered_rule=rules[rules['confidence'] >= 0.02]

#print(filtered_rule)
print(filtered_rule[['antecedents', 'consequents', 'support', 'confidence', 'lift']].sort_values('lift', ascending=False).head(10))

                            antecedents                         consequents  \
341               (milk, mineral water)           (frozen vegetables, soup)
344           (frozen vegetables, soup)               (milk, mineral water)
331      (frozen vegetables, olive oil)               (milk, mineral water)
328               (milk, mineral water)      (frozen vegetables, olive oil)
174  (whole wheat pasta, mineral water)                         (olive oil)
177                         (olive oil)  (whole wheat pasta, mineral water)
242      (chocolate, frozen vegetables)             (shrimp, mineral water)
243             (shrimp, mineral water)      (chocolate, frozen vegetables)
343  (frozen vegetables, mineral water)                        (milk, soup)
342                        (milk, soup)  (frozen vegetables, mineral water)

      support  confidence      lift
341  0.003066    0.063889  7.987176
344  0.003066    0.383333  7.987176
331  0.003333    0.294118  6.128268
328  0.003333    0.069444  6.128268
174  0.003866    0.402778  6.115863
177  0.003866    0.058704  6.115863
242  0.003200    0.139535  5.913283
243  0.003200    0.135593  5.913283
343  0.003066    0.085821  5.646864
342  0.003066    0.201754  5.646864

In [ ]:
# Support (0.003): This requires an item combination to appear at least 22 times in the dataset. Setting this too high (e.g., 0.05) would only return very common items like "mineral water," missing the "hidden" associations.

# Confidence (0.2): This means that in 20% of the cases where the first item is bought, the second is also bought. This is a standard starting point for retail data where basket variety is high.

# Lift (> 3): This is the most critical threshold. A lift of 3 means the items are bought together 3 times more often than would be expected by random chance. Any lift > 1 indicates a positive relationship.

Analysis and Interpretation:
•	Analyse the generated rules to identify interesting patterns and relationships between the products.
•	Interpret the results and provide insights into customer purchasing behaviour based on the discovered rules.

ANALYSIS
* The strongest association in the data is between (Frozen Vegetables, Soup) and (Milk, Mineral Water). With a Lift of approx. 8, a customer buying the soup/vegetable combo is 8 times more likely to also have milk and mineral water in their cart than a normal shopper.

* There is a very strong link between (Whole Wheat Pasta, Mineral Water) and (Olive Oil).
The Confidence (0.40) for rule 174 indicates that 40% of people who buy whole wheat pasta and mineral water also buy olive oil. 

* The relationship between (Chocolate, Frozen Vegetables) and (Shrimp, Mineral Water) suggests a "Dinner Night" basket. It indicates a protein source (shrimp) with a treat (chocolate).


INTERPRETATION
* Shoppers aren't just buying random items, they are shopping for ingredients. The high lift for Olive Oil when combined with Whole Wheat Pasta suggests that these customers are likely health-conscious and are buying ingrediats for a Mediterranean-style meal.

So, putting olive oil near to whole wheat pasta can increase sales. OR putting clear signage like 'Don't forget olive oil" can boost sales.
Also, small discount on the oil when buying the pasta would attract many shoppers.

* Mineral Water appears in almost every top rule. However, it is rarely the only item.
Thus, Placing mineral water near the billing section can make the customers buy them to round of their order.

* Frozen Vegetables appear in three of your top 10 rules (linked to soup, milk, and chocolate). 
Putting frozen vegetables on sale, can likely triggering the purchase of milk, soup, and shrimp because they are so mathematically tied together.

1.	What is lift and why is it important in Association rules?

Lift measures how many times more often antecedent(if) and consequent(then) occur together than we would expect if they were statistically independent. It is the ratio of the observed support to the expected support.

Lift= confidence(X -> Y)/support(Y)

Lift > 1: There is a positive association. Item X "pulls" Item Y into the cart. The higher the value, the stronger the relationship.
Lift = 1: The items are independent. Buying X has no effect on the probability of buying Y.
Lift < 1: There is a negative association. This means the items are "substitutes" or "repel" each other

IMPORTANCE:
1.Differentiates Meaningful Rules: It determines if a rule is actually strong, or just a result of high-frequency items
2.Identifies "Interestingness": A rule might have high confidence just because the consequent is common. High lift tells you the antecedent significantly increases the probability of the consequent, which is useful for recommendation engines.
3.Reveals Negative Associations: Lift values less than 1 show that two items are less likely to be bought together, aiding in inventory decisions.
4.Avoids Spurious Associations: It filters out rules that occur by chance, distinguishing between true customer purchasing patterns and random coincidence.

2.	What is support and Confidence. How do you calculate them?

Support is the Fraction of transactions containing the itemsets in both X and Y. It measures how frequently the combination appears in the data.
Support(X->Y)=no: of transactions with (XUY)/Total no:of transactions

Confidence is the Probability that transactions with X also include Y. It measures the reliability of the inference.
Confidence(X->Y)=Support(XUY)/support(X)

In [ ]:
3.	What are some limitations or challenges of Association rules mining?

* Large Number of Rules: Can generate many rules, including trivial or redundant ones, making interpretation hard.
* Support Threshold Sensitivity: High support thresholds miss interesting but infrequent patterns; low thresholds generate too many rules.
* Not Suitable for Continuous Variables: Primarily designed for categorical data, Requires discretization or binning before use with numerical attributes.
* Computationally Expensive: Performance degrades on very large or dense datasets due to combinatorial explosion.
* Statistical Significance: High confidence doesn’t guarantee a meaningful rule; domain knowledge is essential to validate findings.